### ISSUE TITLE
Haddock links broken for certain external dependencies

### ISSUE THREAD

**Issue by vreuter** [tweag/funflow2#112]
Not sure the full extent of the issue, but for the `kernmantle-caching` [docs](https://tweag.github.io/funflow2/api/kernmantle-caching/html/Control-Kernmantle-Caching.html), links to `Store` (provided by the `store` package) are broken. Specifically, the URL doesn't change when a link is clicked. See, for example clicking `Store` in the constraints withing the `usingStore` and `caching` signatures.

**Comment by dorranh** [comment]
This is the tricky thing with self hosting as opposed to publishing on hackage - if you want to have the full haddocks for all of your dependencies you have to build / host them. So far I've tried to keep things fairly minimal, focusing on kernmantle and the libraries in this repo. We can add store if you think it would be valuable - the libraries which have their documentation generated are specified here.
https://github.com/tweag/funflow2/blob/cd360299f10a5c65e75b734540f30d037585f62e/nix/overlays.nix#L93

**Comment by vreuter** [comment]
> the libraries which have their documentation generated are specified here.
> 
> https://github.com/tweag/funflow2/blob/cd360299f10a5c65e75b734540f30d037585f62e/nix/overlays.nix#L93

Cool, thanks for pointing this out!

OK no I think it's good as-is then. I just noticed it when I tried to follow the `Store` link yesterday, but I don't think there's anything special about the `store` dependency that should privilege it over other dependencies that we're not building and hosting docs for now.
