### ISSUE TITLE
Local Hoogle index?

### ISSUE THREAD

**Issue by vreuter** [tweag/funflow2#114]
Could we add something like this?
https://input-output-hk.github.io/haskell.nix/tutorials/development/#how-to-get-a-local-hoogle-index

**Comment by dorranh** [comment]
Ah so I think this is already possible using the build shell: 

```console
nix-shell shell-stack.nix
hoogle server --local
```

Note that this will not include funflow itself, since it shellFor only provides the dependencies of the package you are working on.

**Comment by vreuter** [comment]
I see, yes I'd missed that it's not for the package under development.
