### ISSUE TITLE
Write docker logs to result store item

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/funflow2#61]
Following #59 

https://github.com/tweag/funflow2/pull/59/files#r495892509

make a call to `saveContainerLogs Stdout` and `saveContainerLogs StdErr`

**Comment by dorranh** [comment]
IMO we should only include file-based outputs in the content store outputs for DockerTasks since log outputs may contain random other data which will change the content hash (e.g. log timestamps).

If a future user thinks that this would be helpful, feel free to re-open a feature request for this.
