### ISSUE TITLE
Tutorial: Makefile

### ISSUE THREAD

**Issue by dorranh** [tweag/funflow2#80]
Funflow v1 has a nice example of creating a workflow which acts as an alternative `make`. https://github.com/tweag/funflow/tree/master/funflow-examples/makefile-tool. We should re-create this tutorial in funflow2.

**Comment by vreuter** [comment]
Looks solved by https://github.com/tweag/funflow2/commit/642cbb6a1eb3c03b31fe32d22886e4eba4b877cc

**Comment by dorranh** [comment]
Thanks for taking a look, @vreuter. I think that we might still be one example short. The original funflow has this little application which emulates make which we can try to port to funflow2 https://github.com/tweag/funflow/tree/master/funflow-examples/makefile-tool

**Comment by vreuter** [comment]
Oh OK sounds good!
