### ISSUE TITLE
Update development guide

### ISSUE THREAD

**Issue by dorranh** [tweag/funflow2#92]
The `DEVELOPMENT.md` is a bit out of date (this section specifically: https://github.com/tweag/funflow2/blob/master/docs/DEVELOPMENT.md#updating-the-nix-build)

**Comment by vreuter** [comment]
Oh 1 additional thing from what I mentioned in #91 is the the "Update Locally" section. I think the `funflow.components.library` attribute is now just `funflow`?

**Comment by dorranh** [comment]
@vreuter, nice catch. That's correct - the correct attribute is `funflow`.
