### ISSUE TITLE
Hide CLI config?

### ISSUE THREAD

**Issue by vreuter** [tweag/funflow2#99]
There are at least a [couple](https://github.com/tweag/funflow2/blob/master/funflow/src/Funflow/Run.hs#L101) of [notes](https://github.com/tweag/funflow2/blob/master/funflow/src/Funflow/Run.hs#L145-L146) in `Run.hs` about lack of support for config via CLI. Should we not export and not put in public-facing docs the relevant types until they're supported by implementation in the runner?

**Comment by vreuter** [comment]
@dorranh I assigned you since the question is for you, but I'm happy to make w/e change you see fit.

**Comment by dorranh** [comment]
You know, I could have sworn that I had merged this. This does in need to be done and has been implemented here: https://github.com/tweag/funflow2/commit/81a719eaa21db649fcf934909bc059172d28006d
